version: "3.8"

services:
  database:
    image: postgres:14.1-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password0701
      - POSTGRES_DB=practice
    ports:
      - '5432:5432/tcp'
  cache:
    image: redis:7.0-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
  service-1:
    build: ./first-service
    container_name: service-1
    ports:
      - '8089:8089'
  service-2:
    build: ./second-service
    container_name: service-2
    ports:
      - '8081:8081'
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  grafana:
    image: grafana/grafana:9.3.0
    container_name: grafana_zipkin
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
#    volumes:
#      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
#      - ./grafana:/var/lib/grafana/data
